name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out github repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run integration tests
        run: npm run test:integration
        timeout-minutes: 15
        env:
          ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY}}
          BARTER_AUTH_HEADER: ${{secrets.BARTER_AUTH_HEADER}}
          BARTER_CUSTOM_SUBDOMAIN: ${{secrets.BARTER_CUSTOM_SUBDOMAIN}}
          CODEX_API_KEY: ${{secrets.CODEX_API_KEY}}
  # integration-quotes:
  #   needs: ['integration']
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out github repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 1

  #     - name: Install node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '18.x'
  #         cache: npm
  #         cache-dependency-path: '**/package-lock.json'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run integration tests
  #       run: npm run test:integration:quotes
  #       timeout-minutes: 15
  #       env:
  #         ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY}}
  #         RANGO_API_KEY: ${{secrets.RANGO_API_KEY}}
  #         BARTER_AUTH_HEADER: ${{secrets.BARTER_AUTH_HEADER}}
  #         BARTER_CUSTOM_SUBDOMAIN: ${{secrets.BARTER_CUSTOM_SUBDOMAIN}}
  #         CI_CONTEXT: true
